const conversations = {
  "intro": [
    { speaker: 1, text: "We have a problem." },
    { speaker: 0, text: "What kind of problem?" },
    { speaker: 1, text: "A huge problem." },
    { speaker: 0, text: "He's back?" },
    { speaker: 1, text: "He's back." },
    { speaker: 0, text: "We all knew this day would come." },
    { speaker: 1, text: "Sooner than I would have hoped for." },
    { speaker: 1, text: "Once you get in, Dr. Drauxbahtz has some new gear for you. I think you'll find it useful." },
    { speaker: 0, text: "I've been preparing for this day. I'll be right over." },
    { speaker: 1, text: "We'll get him this time." },
  ],
  "firstLevel": [
    { speaker: 2, text: "Alright, let's test the waters. Your stealth exoskeleton greatly expands upon your current abilities." },
    { speaker: 2, text: "You should be able to jump much farther and higher than any normal human can." },
    { speaker: 0, text: "Sounds great."},
    { speaker: 0, text: "So, how do I work this thing?"},
    { speaker: 2, text: "See that big arrow on your HUD? When it points to the direction you want to jump [CLICK & HOLD]." },
    { speaker: 2, text: "While you [CLICK & HOLD] that big arrow will grow, indicating how strong your jump will be." },
    { speaker: 2, text: "Once the you feel your jump is strong enough [RELEASE CLICK] to jump. Easy peasy."},
    { speaker: 0, text: "Easy peasy, right. I'll give it a shot. Thanks for the upgrades, Dr. Drauxbahtz."},
    { speaker: 2, text: "You got it! And please, you can call me Hugh."},
  ],
  "firstStander": [
    { speaker: 0, text: "What is THAT thing?" },
    { speaker: 2, text: "I guess I don't know really what it is, but we've been calling them tallbots. On account of them being tall." },
    { speaker: 0, text: "I see." },
    { speaker: 2, text: "Well, this is the perfect opportunity to test out how your exoskeleton enhances your kick strength."},
    { speaker: 0, text: "I like the sound of that."},
    { speaker: 2, text: "Just jump to it and let your suit do the rest." },
  ],
  "firstFlier": [
    { speaker: 0, text: "Okay, now what about this guy?" },
    { speaker: 2, text: "We call those fliers, on account of them--" },
    { speaker: 0, text: "Yeah, I get it." },
    { speaker: 0, text: "I'm gonna kick it." },
    { speaker: 2, text: "You actually can't kick these."},
    { speaker: 0, text: "Why not?"},
    { speaker: 2, text: "[PHYSICS EXPLANATION]" },
    { speaker: 0, text: "Makes perfect sense."},
    { speaker: 2, text: "Not to worry, I have another tool for you to try: Energy kunai." },
    { speaker: 0, text: "Keep going."},
    { speaker: 2, text: "Here's how it works, while you are in the air [CLICK] to enter a targeting mode." },
    { speaker: 2, text: "You'll see a targeting arrow on your HUD. When it is pointing at a target [CLICK] to throw an energy kunai." },
    { speaker: 2, text: "The kunai will work on the tallbots as well." },
    { speaker: 0, text: "Excellent." },
    { speaker: 2, text: "Oh, and in a single jump you can throw as many kunai as you have charged up"},
  ],
  "checkIn": [
    { speaker: 1, text: "You're doing a great job cleaning up the city. Keep up the good work." },
    { speaker: 0, text: "It's got to be done" },
  ],
  "teleport": [
    { speaker: 0, text: "Uhh, what just happened?" },
    { speaker: 2, text: "Haha, it worked!"},
    { speaker: 0, text: "And what is \"it\" exactly?"},
    { speaker: 2, text: "I added an emergency teleportation system. It returns you to a place of safety when it detects you are in imminent mortal danger."},
    { speaker: 0, text: "I guess I owe you one."},
    { speaker: 2, text: "Before you get too excited, you should know that this teleportation system uses a LOT of energy. You can only use it a limited number of times before it needs to recharge."},
    { speaker: 0, text: "So if this uses energy, does using have a negative impact on the weaponry in this thing?"},
    { speaker: 2, text: "Good question, and nope!"},
    { speaker: 0, text: "It seems like it would though."},
    { speaker: 2, text: "[A GENERIC HAND-WAVY REASON]"},
    { speaker: 0, text: "Uh huh..."},

  ],
  "bossCinematic1": [
    { speaker: 1, text: "How's everything going? Have you seen him yet?" },
    { speaker: 0, text: "No, not yet. But I'm ready."},
    { speaker: 1, text: "You should be proud of the work you've done tonight. Things have certainly quieted down a bit."},
    { speaker: 0, text: "Yeah... things are quiet..."}, 
    { speaker: 0, text: "...too quiet."}
  ],
  "bossCinematic2": [
    { speaker: 0, text: "What was that?!" },
  ],
  "bossCinematic3": [
    { speaker: 0, text: "Oh boy." },
  ],
  "bossCinematic4": [
    { speaker: 0, text: "Hey boss." },
    { speaker: 0, text: "I found him." },
    { speaker: 1, text: "You did?! Godspeed, my friend."},
    { speaker: 2, text: "Just one thing! We in the scientific community, know very little about him, but based on some of the models we ran--" },
    { speaker: 0, text: "Please get to the point."},
    { speaker: 2, text: "Right, sorry. His only apparent weakness appears to be his EYE."},
    { speaker: 2, text: "His EYE."},
    { speaker: 0, text: "Weak point, eye. Got it."},
    { speaker: 2, text: "Oh, but only while he's charging or shooting that laser! Good luck!"},
    { speaker: 0, text: "LASER?! Nobody said anything about a laser!"},
    { speaker: 0, text: "Hugh."},
    { speaker: 0, text: "Hugh?"},
    { speaker: 0, text: "HUGH!!!!"},
  ],
  "death": [
    { speaker: 0, text: "Uh oh."},
    { speaker: 3, text: "NOOOOOOOOOO!!!!!!"},
  ],
};

export default conversations;
